/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.jhu.cvrg.waveform.main.dbpersistence.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfo;
import edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfoModel;
import edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FilesInfo service. Represents a row in the &quot;Database_FilesInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FilesInfoImpl}.
 * </p>
 *
 * @author bbenite1
 * @see FilesInfoImpl
 * @see edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfo
 * @see edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfoModel
 * @generated
 */
@JSON(strict = true)
public class FilesInfoModelImpl extends BaseModelImpl<FilesInfo>
	implements FilesInfoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a files info model instance should use the {@link edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfo} interface instead.
	 */
	public static final String TABLE_NAME = "Database_FilesInfo";
	public static final Object[][] TABLE_COLUMNS = {
			{ "DocumentID", Types.VARCHAR },
			{ "FileListID", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Database_FilesInfo (DocumentID VARCHAR(75) not null primary key,FileListID VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Database_FilesInfo";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfo"),
			true);
	public static long FILELISTID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FilesInfo toModel(FilesInfoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FilesInfo model = new FilesInfoImpl();

		model.setDocumentID(soapModel.getDocumentID());
		model.setFileListID(soapModel.getFileListID());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FilesInfo> toModels(FilesInfoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FilesInfo> models = new ArrayList<FilesInfo>(soapModels.length);

		for (FilesInfoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfo"));

	public FilesInfoModelImpl() {
	}

	public String getPrimaryKey() {
		return _DocumentID;
	}

	public void setPrimaryKey(String primaryKey) {
		setDocumentID(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _DocumentID;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return FilesInfo.class;
	}

	public String getModelClassName() {
		return FilesInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("DocumentID", getDocumentID());
		attributes.put("FileListID", getFileListID());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String DocumentID = (String)attributes.get("DocumentID");

		if (DocumentID != null) {
			setDocumentID(DocumentID);
		}

		String FileListID = (String)attributes.get("FileListID");

		if (FileListID != null) {
			setFileListID(FileListID);
		}
	}

	@JSON
	public String getDocumentID() {
		if (_DocumentID == null) {
			return StringPool.BLANK;
		}
		else {
			return _DocumentID;
		}
	}

	public void setDocumentID(String DocumentID) {
		_DocumentID = DocumentID;
	}

	@JSON
	public String getFileListID() {
		if (_FileListID == null) {
			return StringPool.BLANK;
		}
		else {
			return _FileListID;
		}
	}

	public void setFileListID(String FileListID) {
		_columnBitmask |= FILELISTID_COLUMN_BITMASK;

		if (_originalFileListID == null) {
			_originalFileListID = _FileListID;
		}

		_FileListID = FileListID;
	}

	public String getOriginalFileListID() {
		return GetterUtil.getString(_originalFileListID);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public FilesInfo toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (FilesInfo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		FilesInfoImpl filesInfoImpl = new FilesInfoImpl();

		filesInfoImpl.setDocumentID(getDocumentID());
		filesInfoImpl.setFileListID(getFileListID());

		filesInfoImpl.resetOriginalValues();

		return filesInfoImpl;
	}

	public int compareTo(FilesInfo filesInfo) {
		String primaryKey = filesInfo.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		FilesInfo filesInfo = null;

		try {
			filesInfo = (FilesInfo)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = filesInfo.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		FilesInfoModelImpl filesInfoModelImpl = this;

		filesInfoModelImpl._originalFileListID = filesInfoModelImpl._FileListID;

		filesInfoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FilesInfo> toCacheModel() {
		FilesInfoCacheModel filesInfoCacheModel = new FilesInfoCacheModel();

		filesInfoCacheModel.DocumentID = getDocumentID();

		String DocumentID = filesInfoCacheModel.DocumentID;

		if ((DocumentID != null) && (DocumentID.length() == 0)) {
			filesInfoCacheModel.DocumentID = null;
		}

		filesInfoCacheModel.FileListID = getFileListID();

		String FileListID = filesInfoCacheModel.FileListID;

		if ((FileListID != null) && (FileListID.length() == 0)) {
			filesInfoCacheModel.FileListID = null;
		}

		return filesInfoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{DocumentID=");
		sb.append(getDocumentID());
		sb.append(", FileListID=");
		sb.append(getFileListID());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("edu.jhu.cvrg.waveform.main.dbpersistence.model.FilesInfo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>DocumentID</column-name><column-value><![CDATA[");
		sb.append(getDocumentID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FileListID</column-name><column-value><![CDATA[");
		sb.append(getFileListID());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FilesInfo.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			FilesInfo.class
		};
	private String _DocumentID;
	private String _FileListID;
	private String _originalFileListID;
	private long _columnBitmask;
	private FilesInfo _escapedModelProxy;
}