/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.jhu.cvrg.waveform.main.dbpersistence.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AnnotationInfo service. Represents a row in the &quot;Database_AnnotationInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.AnnotationInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.AnnotationInfoImpl}.
 * </p>
 *
 * @author bbenite1
 * @see AnnotationInfo
 * @see edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.AnnotationInfoImpl
 * @see edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.AnnotationInfoModelImpl
 * @generated
 */
public interface AnnotationInfoModel extends BaseModel<AnnotationInfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a annotation info model instance should use the {@link AnnotationInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this annotation info.
	 *
	 * @return the primary key of this annotation info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this annotation info.
	 *
	 * @param primaryKey the primary key of this annotation info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the annotation i d of this annotation info.
	 *
	 * @return the annotation i d of this annotation info
	 */
	public long getAnnotationID();

	/**
	 * Sets the annotation i d of this annotation info.
	 *
	 * @param AnnotationID the annotation i d of this annotation info
	 */
	public void setAnnotationID(long AnnotationID);

	/**
	 * Returns the created by of this annotation info.
	 *
	 * @return the created by of this annotation info
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this annotation info.
	 *
	 * @param CreatedBy the created by of this annotation info
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the annotation type of this annotation info.
	 *
	 * @return the annotation type of this annotation info
	 */
	@AutoEscape
	public String getAnnotationType();

	/**
	 * Sets the annotation type of this annotation info.
	 *
	 * @param AnnotationType the annotation type of this annotation info
	 */
	public void setAnnotationType(String AnnotationType);

	/**
	 * Returns the name of this annotation info.
	 *
	 * @return the name of this annotation info
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this annotation info.
	 *
	 * @param Name the name of this annotation info
	 */
	public void setName(String Name);

	/**
	 * Returns the bioportal reference of this annotation info.
	 *
	 * @return the bioportal reference of this annotation info
	 */
	@AutoEscape
	public String getBioportalReference();

	/**
	 * Sets the bioportal reference of this annotation info.
	 *
	 * @param BioportalReference the bioportal reference of this annotation info
	 */
	public void setBioportalReference(String BioportalReference);

	/**
	 * Returns the lead of this annotation info.
	 *
	 * @return the lead of this annotation info
	 */
	@AutoEscape
	public String getLead();

	/**
	 * Sets the lead of this annotation info.
	 *
	 * @param Lead the lead of this annotation info
	 */
	public void setLead(String Lead);

	/**
	 * Returns the starting coordinate i d of this annotation info.
	 *
	 * @return the starting coordinate i d of this annotation info
	 */
	public long getStartingCoordinateID();

	/**
	 * Sets the starting coordinate i d of this annotation info.
	 *
	 * @param StartingCoordinateID the starting coordinate i d of this annotation info
	 */
	public void setStartingCoordinateID(long StartingCoordinateID);

	/**
	 * Returns the ending coordinate i d of this annotation info.
	 *
	 * @return the ending coordinate i d of this annotation info
	 */
	public long getEndingCoordinateID();

	/**
	 * Sets the ending coordinate i d of this annotation info.
	 *
	 * @param EndingCoordinateID the ending coordinate i d of this annotation info
	 */
	public void setEndingCoordinateID(long EndingCoordinateID);

	/**
	 * Returns the unit of measurement of this annotation info.
	 *
	 * @return the unit of measurement of this annotation info
	 */
	@AutoEscape
	public String getUnitOfMeasurement();

	/**
	 * Sets the unit of measurement of this annotation info.
	 *
	 * @param UnitOfMeasurement the unit of measurement of this annotation info
	 */
	public void setUnitOfMeasurement(String UnitOfMeasurement);

	/**
	 * Returns the description of this annotation info.
	 *
	 * @return the description of this annotation info
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this annotation info.
	 *
	 * @param Description the description of this annotation info
	 */
	public void setDescription(String Description);

	/**
	 * Returns the value of this annotation info.
	 *
	 * @return the value of this annotation info
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this annotation info.
	 *
	 * @param Value the value of this annotation info
	 */
	public void setValue(String Value);

	/**
	 * Returns the document record i d of this annotation info.
	 *
	 * @return the document record i d of this annotation info
	 */
	public long getDocumentRecordID();

	/**
	 * Sets the document record i d of this annotation info.
	 *
	 * @param DocumentRecordID the document record i d of this annotation info
	 */
	public void setDocumentRecordID(long DocumentRecordID);

	/**
	 * Returns the timestamp of this annotation info.
	 *
	 * @return the timestamp of this annotation info
	 */
	public Date getTimestamp();

	/**
	 * Sets the timestamp of this annotation info.
	 *
	 * @param Timestamp the timestamp of this annotation info
	 */
	public void setTimestamp(Date Timestamp);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AnnotationInfo annotationInfo);

	public int hashCode();

	public CacheModel<AnnotationInfo> toCacheModel();

	public AnnotationInfo toEscapedModel();

	public String toString();

	public String toXmlString();
}