/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.jhu.cvrg.waveform.main.dbpersistence.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Coordinate service. Represents a row in the &quot;Database_Coordinate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.CoordinateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.CoordinateImpl}.
 * </p>
 *
 * @author bbenite1
 * @see Coordinate
 * @see edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.CoordinateImpl
 * @see edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.CoordinateModelImpl
 * @generated
 */
public interface CoordinateModel extends BaseModel<Coordinate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a coordinate model instance should use the {@link Coordinate} interface instead.
	 */

	/**
	 * Returns the primary key of this coordinate.
	 *
	 * @return the primary key of this coordinate
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this coordinate.
	 *
	 * @param primaryKey the primary key of this coordinate
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the coordinate i d of this coordinate.
	 *
	 * @return the coordinate i d of this coordinate
	 */
	@AutoEscape
	public String getCoordinateID();

	/**
	 * Sets the coordinate i d of this coordinate.
	 *
	 * @param CoordinateID the coordinate i d of this coordinate
	 */
	public void setCoordinateID(String CoordinateID);

	/**
	 * Returns the x coordinate of this coordinate.
	 *
	 * @return the x coordinate of this coordinate
	 */
	public double getXCoordinate();

	/**
	 * Sets the x coordinate of this coordinate.
	 *
	 * @param xCoordinate the x coordinate of this coordinate
	 */
	public void setXCoordinate(double xCoordinate);

	/**
	 * Returns the y coordinate of this coordinate.
	 *
	 * @return the y coordinate of this coordinate
	 */
	public double getYCoordinate();

	/**
	 * Sets the y coordinate of this coordinate.
	 *
	 * @param yCoordinate the y coordinate of this coordinate
	 */
	public void setYCoordinate(double yCoordinate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Coordinate coordinate);

	public int hashCode();

	public CacheModel<Coordinate> toCacheModel();

	public Coordinate toEscapedModel();

	public String toString();

	public String toXmlString();
}