/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.jhu.cvrg.waveform.main.dbpersistence.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DocumentRecord service. Represents a row in the &quot;Database_DocumentRecord&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.DocumentRecordModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.DocumentRecordImpl}.
 * </p>
 *
 * @author bbenite1
 * @see DocumentRecord
 * @see edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.DocumentRecordImpl
 * @see edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.DocumentRecordModelImpl
 * @generated
 */
public interface DocumentRecordModel extends BaseModel<DocumentRecord> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document record model instance should use the {@link DocumentRecord} interface instead.
	 */

	/**
	 * Returns the primary key of this document record.
	 *
	 * @return the primary key of this document record
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this document record.
	 *
	 * @param primaryKey the primary key of this document record
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the record i d of this document record.
	 *
	 * @return the record i d of this document record
	 */
	@AutoEscape
	public String getRecordID();

	/**
	 * Sets the record i d of this document record.
	 *
	 * @param RecordID the record i d of this document record
	 */
	public void setRecordID(String RecordID);

	/**
	 * Returns the record name of this document record.
	 *
	 * @return the record name of this document record
	 */
	@AutoEscape
	public String getRecordName();

	/**
	 * Sets the record name of this document record.
	 *
	 * @param RecordName the record name of this document record
	 */
	public void setRecordName(String RecordName);

	/**
	 * Returns the user i d of this document record.
	 *
	 * @return the user i d of this document record
	 */
	@AutoEscape
	public String getUserID();

	/**
	 * Sets the user i d of this document record.
	 *
	 * @param UserID the user i d of this document record
	 */
	public void setUserID(String UserID);

	/**
	 * Returns the subject i d of this document record.
	 *
	 * @return the subject i d of this document record
	 */
	@AutoEscape
	public String getSubjectID();

	/**
	 * Sets the subject i d of this document record.
	 *
	 * @param SubjectID the subject i d of this document record
	 */
	public void setSubjectID(String SubjectID);

	/**
	 * Returns the original format of this document record.
	 *
	 * @return the original format of this document record
	 */
	@AutoEscape
	public String getOriginalFormat();

	/**
	 * Sets the original format of this document record.
	 *
	 * @param OriginalFormat the original format of this document record
	 */
	public void setOriginalFormat(String OriginalFormat);

	/**
	 * Returns the sampling rate of this document record.
	 *
	 * @return the sampling rate of this document record
	 */
	public double getSamplingRate();

	/**
	 * Sets the sampling rate of this document record.
	 *
	 * @param SamplingRate the sampling rate of this document record
	 */
	public void setSamplingRate(double SamplingRate);

	/**
	 * Returns the file tree path of this document record.
	 *
	 * @return the file tree path of this document record
	 */
	@AutoEscape
	public String getFileTreePath();

	/**
	 * Sets the file tree path of this document record.
	 *
	 * @param FileTreePath the file tree path of this document record
	 */
	public void setFileTreePath(String FileTreePath);

	/**
	 * Returns the lead count of this document record.
	 *
	 * @return the lead count of this document record
	 */
	public int getLeadCount();

	/**
	 * Sets the lead count of this document record.
	 *
	 * @param LeadCount the lead count of this document record
	 */
	public void setLeadCount(int LeadCount);

	/**
	 * Returns the number of points of this document record.
	 *
	 * @return the number of points of this document record
	 */
	public int getNumberOfPoints();

	/**
	 * Sets the number of points of this document record.
	 *
	 * @param NumberOfPoints the number of points of this document record
	 */
	public void setNumberOfPoints(int NumberOfPoints);

	/**
	 * Returns the date of upload of this document record.
	 *
	 * @return the date of upload of this document record
	 */
	public Date getDateOfUpload();

	/**
	 * Sets the date of upload of this document record.
	 *
	 * @param DateOfUpload the date of upload of this document record
	 */
	public void setDateOfUpload(Date DateOfUpload);

	/**
	 * Returns the age of this document record.
	 *
	 * @return the age of this document record
	 */
	public int getAge();

	/**
	 * Sets the age of this document record.
	 *
	 * @param Age the age of this document record
	 */
	public void setAge(int Age);

	/**
	 * Returns the gender of this document record.
	 *
	 * @return the gender of this document record
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this document record.
	 *
	 * @param Gender the gender of this document record
	 */
	public void setGender(String Gender);

	/**
	 * Returns the date of recording of this document record.
	 *
	 * @return the date of recording of this document record
	 */
	public Date getDateOfRecording();

	/**
	 * Sets the date of recording of this document record.
	 *
	 * @param DateOfRecording the date of recording of this document record
	 */
	public void setDateOfRecording(Date DateOfRecording);

	/**
	 * Returns the adu gain of this document record.
	 *
	 * @return the adu gain of this document record
	 */
	public double getAduGain();

	/**
	 * Sets the adu gain of this document record.
	 *
	 * @param AduGain the adu gain of this document record
	 */
	public void setAduGain(double AduGain);

	/**
	 * Returns the file list i d of this document record.
	 *
	 * @return the file list i d of this document record
	 */
	@AutoEscape
	public String getFileListID();

	/**
	 * Sets the file list i d of this document record.
	 *
	 * @param FileListID the file list i d of this document record
	 */
	public void setFileListID(String FileListID);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DocumentRecord documentRecord);

	public int hashCode();

	public CacheModel<DocumentRecord> toCacheModel();

	public DocumentRecord toEscapedModel();

	public String toString();

	public String toXmlString();
}