/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.jhu.cvrg.waveform.main.dbpersistence.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FilesInfo service. Represents a row in the &quot;Database_FilesInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.FilesInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.FilesInfoImpl}.
 * </p>
 *
 * @author bbenite1
 * @see FilesInfo
 * @see edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.FilesInfoImpl
 * @see edu.jhu.cvrg.waveform.main.dbpersistence.model.impl.FilesInfoModelImpl
 * @generated
 */
public interface FilesInfoModel extends BaseModel<FilesInfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a files info model instance should use the {@link FilesInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this files info.
	 *
	 * @return the primary key of this files info
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this files info.
	 *
	 * @param primaryKey the primary key of this files info
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the document i d of this files info.
	 *
	 * @return the document i d of this files info
	 */
	@AutoEscape
	public String getDocumentID();

	/**
	 * Sets the document i d of this files info.
	 *
	 * @param DocumentID the document i d of this files info
	 */
	public void setDocumentID(String DocumentID);

	/**
	 * Returns the file list i d of this files info.
	 *
	 * @return the file list i d of this files info
	 */
	@AutoEscape
	public String getFileListID();

	/**
	 * Sets the file list i d of this files info.
	 *
	 * @param FileListID the file list i d of this files info
	 */
	public void setFileListID(String FileListID);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FilesInfo filesInfo);

	public int hashCode();

	public CacheModel<FilesInfo> toCacheModel();

	public FilesInfo toEscapedModel();

	public String toString();

	public String toXmlString();
}